[package]
name = "sbvc_lib"
description = "Backend for Single Binary file Version Control system"
readme = "README.md"
repository = "https://github.com/Daniikk1012/sbvc_lib"
version = "0.5.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
nelf = "0.1"
wgdiff = "0.4"
